version: '3.8'
services:
  flask-app:
    image: flask-app
    ports:
      - "4000:80"
    environment:
      AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-west-1
